# Generated by Django 3.1.1 on 2020-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mento_math',
        ),
        migrations.RemoveField(
            model_name='usermento',
            name='mento_math',
        ),
        migrations.AddField(
            model_name='user',
            name='mento_basicEngineering',
            field=models.BooleanField(default=False, verbose_name='기초공학설계'),
        ),
        migrations.AddField(
            model_name='user',
            name='mento_principlesodEconomics1',
            field=models.BooleanField(default=False, verbose_name='경제학원론1'),
        ),
        migrations.AddField(
            model_name='user',
            name='mento_principlesodEconomics2',
            field=models.BooleanField(default=False, verbose_name='경제학원론2'),
        ),
        migrations.AddField(
            model_name='user',
            name='mento_univMath',
            field=models.BooleanField(default=False, verbose_name='대학수학'),
        ),
        migrations.AddField(
            model_name='usermento',
            name='mento_basicEngineering',
            field=models.BooleanField(default=False, verbose_name='기초공학설계'),
        ),
        migrations.AddField(
            model_name='usermento',
            name='mento_principlesodEconomics1',
            field=models.BooleanField(default=False, verbose_name='경제학원론1'),
        ),
        migrations.AddField(
            model_name='usermento',
            name='mento_principlesodEconomics2',
            field=models.BooleanField(default=False, verbose_name='경제학원론2'),
        ),
        migrations.AddField(
            model_name='usermento',
            name='mento_univMath',
            field=models.BooleanField(default=False, verbose_name='대학수학'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mento_GC',
            field=models.BooleanField(default=False, verbose_name='고급응용 C프로그래밍 멘토'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mento_basicC',
            field=models.BooleanField(default=False, verbose_name='C언어 기초 멘토'),
        ),
        migrations.AlterField(
            model_name='usermento',
            name='mento_GC',
            field=models.BooleanField(default=False, verbose_name='고급응용 C프로그래밍 멘토'),
        ),
        migrations.AlterField(
            model_name='usermento',
            name='mento_basicC',
            field=models.BooleanField(default=False, verbose_name='C언어 기초 멘토'),
        ),
    ]
