# Generated by Django 3.1.1 on 2020-09-10 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mento_GC',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mento_basicC',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mento_computing',
        ),
        migrations.CreateModel(
            name='UserMento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mento_computing', models.BooleanField(default=False, verbose_name='컴퓨팅사고력 멘토')),
                ('mento_basicC', models.BooleanField(default=False, verbose_name='기초C언어 멘토')),
                ('mento_GC', models.BooleanField(default=False, verbose_name='고급응용C프로그래밍 멘토')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
