# Generated by Django 3.1.1 on 2020-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mento_GC',
            field=models.BooleanField(default=False, verbose_name='고급응용C프로그래밍 멘토'),
        ),
        migrations.AddField(
            model_name='user',
            name='mento_basicC',
            field=models.BooleanField(default=False, verbose_name='기초C언어 멘토'),
        ),
        migrations.AddField(
            model_name='user',
            name='mento_computing',
            field=models.BooleanField(default=False, verbose_name='컴퓨팅사고력 멘토'),
        ),
        migrations.AddField(
            model_name='user',
            name='mento_math',
            field=models.BooleanField(default=False, verbose_name='응용수학 멘토'),
        ),
    ]
