# Generated by Django 3.1 on 2020-09-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200901_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_num',
        ),
    ]
