# Generated by Django 3.1.1 on 2020-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200910_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermento',
            name='mento_math',
            field=models.BooleanField(default=False, verbose_name='응용수학 멘토'),
        ),
    ]
