# Generated by Django 3.0.8 on 2020-08-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200803_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', '남성'), ('f', '여성'), ('o', '기타')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mento',
            field=models.BooleanField(default=False, verbose_name='멘토/멘티'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=15, verbose_name='학교'),
        ),
    ]
