# Generated by Django 3.0.8 on 2020-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200804_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_mento',
            field=models.BooleanField(default=False, verbose_name='멘토인 경우 체크해주세요'),
        ),
    ]
