# Generated by Django 3.1.1 on 2020-10-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='account_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='계좌번호'),
        ),
    ]
