# Generated by Django 3.0.8 on 2020-08-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/%Y, %m/'),
        ),
    ]
