# Generated by Django 3.1.1 on 2020-09-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='coupon',
            field=models.IntegerField(default=0, verbose_name='커피'),
        ),
    ]
