# Generated by Django 3.1.1 on 2020-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjects',
            field=models.CharField(choices=[('computing', '컴퓨팅 사고력'), ('basicC', '기초 C언어'), ('GC', '고급응용 C프로그래밍'), ('math', '응용수학')], max_length=30, verbose_name='과목'),
        ),
    ]
