# Generated by Django 3.1.1 on 2020-09-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200915_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='coffee',
            field=models.IntegerField(default=0, verbose_name='커피'),
        ),
    ]
