# Generated by Django 3.1.1 on 2020-09-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200915_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.content'),
        ),
    ]
